# This script contains functions and classes useful for doing data reduction
# of PPMS data, especially that generated by asymmetric delta measurements.


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import glob
from scipy.optimize import curve_fit
from scipy.stats import linregress

import utensils.re_values as ur


def reject_outliers(data, iq_range):
    # Higher iq_range will exclude fewer points.
    # iq_range = 0.5 will give 25, 50, 75%.
    
    pcnt = ( 1. - iq_range ) / 2.

    qlow, median, qhigh = data.quantile([pcnt, 0.5, 1-pcnt])
    iqr = qhigh - qlow 

    return data[(data - median).abs() <= 1.0*iqr].index


class OneDelta:


    def __init__(self, filename):

        self.data = pd.read_csv(filename, sep='\t+', engine='python')
        self.ordinal = ur.get_ordinal(filename)
        self.field = ur.get_field(filename)
        self.temp = ur.get_temp(filename)
        self.current = ur.get_current(filename, units='uA')

    def fit_lin(self, num_consider, num_fit, second_reject=True):

        #print(type(df['Voltage'][-num_fit:]))
        self.ind_norej = reject_outliers(self.data['Voltage'][-num_consider:],
                                         0.85)
        ind_end = np.arange(len(self.data['Voltage']))[num_fit:]
        #ind_end = np.arange(len(df['Voltage']))[-2*num_fit:-num_fit]
        ind_tofit = np.intersect1d(self.ind_norej, ind_end)
        #print(ind_tofit)
        self.result = linregress(self.data['Time'][ind_tofit],
                            self.data['Voltage'][ind_tofit]) 

        #plt.plot(df['Time'][-200:], df['Voltage'][-200:])
        #plt.plot(df['Time'][ind_good], df['Voltage'][ind_good]+12.e-6)


        if second_reject:
            self.data_linsub = (self.data['Voltage'][self.ind_norej] 
                        - self.data['Time'][self.ind_norej]*self.result[0])
            self.ind_norej2 = reject_outliers(self.data_linsub, 0.25)

            '''
            i=0
            if self.field == 1620:

                goodname = False
                while goodname == False:
                    name = ('voltage_trace_1620Oe_'+str(i)+'_'
                            +str(self.ordinal)+'.txt')
                    if os.path.isfile(name):
                        i += 1
                    else:
                        goodname = True

                self.data.to_csv(name, sep='\t', index=False)
                i += 1

                print('Wrote ', i, 'th data file.')

                '''
                #plt.plot(self.data['Time'][self.ind_norej],
                #         self.data['Voltage'][self.ind_norej])
                #plt.show()

            #plt.show()
            self.ind_tofit = np.intersect1d(self.ind_norej2, ind_end)
            self.result2 = linregress(self.data['Time'][self.ind_tofit],
                                      self.data['Voltage'][self.ind_tofit]) 
            
            self.val_lin = (self.result2[0]
                            *self.data['Time'].iloc[-int(num_fit/2)]
                            + self.result2[1])

        else:
            self.val_lin =  (self.result[0]
                            *self.data['Time'].iloc[-int(num_fit/2)]
                            + self.result[1])

class MeasLists:

    def __init__(self, lists):

        self.values = lists[0]
        self.fields = lists[1]
        self.field_inds = lists[2]
        self.ordinals = lists[3]
        
    def sort_by_field(self):

        sort_inds = np.asarray(self.fields).argsort()

        self.values = [self.values[i] for i in sort_inds]
        self.field_inds = [self.field_inds[i] for i in sort_inds]
        self.ordinals = [self.ordinals[i] for i in sort_inds]
        self.fields = [self.fields[i] for i in sort_inds]

class MeasDirectory:

    def __init__(self, globstrs):

        self.fln = glob.glob(globstrs[0])
        self.flp = glob.glob(globstrs[1])

    def organize_by_field(self, filelist, num_consider, num_fit):

        values = []
        fields = []
        field_inds = []
        ordinals = []

        for i in range(len(filelist)):
            mydat = OneDelta(filelist[i])
            mydat.fit_lin(num_consider, num_fit)
            field = mydat.field
            #values.append(mydat.val_lin)
            if field not in fields:
                fields.append(field)
                field_inds.append([i])
                ordinals.append([mydat.ordinal])
                values.append([mydat.val_lin])
            else:
                fldind = fields.index(field)
                field_inds[fldind].append(i)
                ordinals[fldind].append(mydat.ordinal)
                values[fldind].append(mydat.val_lin)

        return values, fields, field_inds, ordinals

    def read_data(self, num_consider, num_fit):

        self.lists_neg = MeasLists(self.organize_by_field(self.fln, 
                                                num_consider, num_fit))
        
        self.lists_pos = MeasLists(self.organize_by_field(self.flp, 
                                                num_consider, num_fit))
 
    def get_indices(self, i, lists):

        field = lists.fields[i]

        mn = max(lists.ordinals[i])+1
        firsts = [i
                  for i, x 
                  in enumerate(lists.ordinals[i]) 
                  if x < (mn-1)/2]

        seconds = [i
                  for i, x 
                  in enumerate(lists.ordinals[i]) 
                  if x > (mn-1)/2]

        final_fst = [lists.field_inds[i][j] for j in firsts]
        final_scd = [lists.field_inds[i][j] for j in seconds]

        #print(field, 'first', final_fst, 'second', final_scd)

        #return final_fst, final_scd
        return firsts, seconds

    def compute_voltages(self):

        num = len(self.lists_neg.fields)
        print('Length is ', num)
        self.values = pd.DataFrame({'Field': pd.Series(
                                                self.lists_neg.fields*2),
                                   'V pos': pd.Series(np.zeros(2*num)),
                                   'V neg': pd.Series(np.zeros(2*num)),
                                   'V diff': pd.Series(np.zeros(2*num)),
                                   'V sum': pd.Series(np.zeros(2*num))
                                   })

        self.lists_neg.sort_by_field()
        self.lists_pos.sort_by_field()
 
        for i in range(num):
            field = self.lists_neg.fields[i]
            
            is_n = self.get_indices(i, self.lists_neg)

            ind_pos = self.lists_pos.fields.index(field)
            is_p = self.get_indices(ind_pos, self.lists_pos)


            mean_neg_1 = np.asarray(self.lists_neg.values[i])[is_n[0]].mean()
            mean_neg_2 = np.asarray(self.lists_neg.values[i])[is_n[1]].mean()


            mean_pos_1 = np.asarray(self.lists_pos.values[i])[is_p[0]].mean()
            mean_pos_2 = np.asarray(self.lists_pos.values[i])[is_p[1]].mean()


            self.values.loc[i, 'Field'] = field
            self.values.loc[2*num-1-i, 'Field'] = field
            self.values.loc[i, 'V neg'] = mean_neg_1
            self.values.loc[i, 'V pos'] = mean_pos_1
            self.values.loc[2*num-1-i, 'V neg'] = mean_neg_2
            self.values.loc[2*num-1-i, 'V pos'] = mean_pos_2

            self.values.loc[i, 'V diff'] = mean_neg_1 - mean_pos_1
            self.values.loc[i, 'V sum'] = mean_neg_1 + mean_pos_1
            self.values.loc[2*num-1-i, 'V diff'] = mean_neg_2 - mean_pos_2
            self.values.loc[2*num-1-i, 'V sum'] = mean_neg_2 + mean_pos_2

        #self.values.sort_values('Field', axis=0, inplace=True)

    def write_data(self, filename):

        self.values.to_csv(filename, sep='\t', index=False)


            







